apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmCharts:
  - name: food-app
    releaseName: food-app
    namespace: recipe
    additionalValuesFiles:
      - ../../../infra/helm/food-app/values-prod.yaml

patchesStrategicMerge:
  - patches/recipe-log-shipper.yaml
