{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-tls
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.gateway.tls.secretName }}
  issuerRef:
    name: {{ .Values.certManager.issuerRef.name }}
    kind: {{ .Values.certManager.issuerRef.kind }}
  dnsNames:
    {{- range .Values.certManager.dnsNames }}
    - {{ . }}
    {{- end }}
{{- end }}
