apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- include "jenkins.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ default (printf "%s-sa" .Release.Name) .Values.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: jenkins
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
            - name: agent
              containerPort: 50000
          env:
            - name: JENKINS_OPTS
              value: {{ .Values.jenkinsOpts | quote }}
            {{- if .Values.plugins.enabled }}
            - name: JENKINS_INSTALL_PLUGINS
              value: /usr/share/jenkins/ref/plugins.txt
            {{- end }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            {{- if .Values.plugins.enabled }}
            - name: jenkins-plugins
              mountPath: /usr/share/jenkins/ref/plugins.txt
              subPath: plugins.txt
              readOnly: true
            {{- end }}
            {{- if .Values.secretsManifests.enabled }}
            - name: jenkins-secrets-manifests
              mountPath: {{ .Values.secretsManifests.mountPath }}
              readOnly: true
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-jenkins-home
        {{- if .Values.plugins.enabled }}
        - name: jenkins-plugins
          configMap:
            name: {{ .Release.Name }}-plugins
        {{- end }}
        {{- if .Values.secretsManifests.enabled }}
        - name: jenkins-secrets-manifests
          configMap:
            name: {{ .Release.Name }}-secrets-manifests
        {{- end }}
