{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-controller
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-controller
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "jenkins.serviceAccountName" . }}
    namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-controller
{{- end }}
