{{- if .Values.secretsManifests.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-secrets-manifests
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
data:
  {{- range $name, $content := .Values.secretsManifests.files }}
  {{ $name }}: |
{{ $content | indent 4 }}
  {{- end }}
{{- end }}
