apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: recipe

helmGlobals:
  chartHome: ../../infra/helm

helmCharts:
  - name: food-app
    releaseName: food-app
    namespace: recipe
    valuesFile: ../../infra/helm/food-app/values.yaml
