global:
  imageTag: "dev"
  environment: "dev"

seed:
  enabled: true
  confirm: true
  allowInProd: false

secrets:
  enabled: true

gateway:
  enabled: true
  listener:
    hostname: recipe-dev.dishsharing.com
  tls:
    enabled: true
    secretName: recipe-dev-tls
  hostnames:
    - recipe-dev.dishsharing.com
