global:
  imageTag: "staging"
  environment: "staging"

seed:
  enabled: false

# secrets:
#   external:
#     enabled: true
#     manifests: |
#       # ExternalSecret/SecretStore manifests for staging

ingress:
  enabled: false
  host: recipe.staging

gateway:
  enabled: true
  hostnames:
    - recipe.staging
