{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "food-app.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
    - name: {{ .Values.gateway.listener.name }}
      protocol: {{ .Values.gateway.listener.protocol }}
      port: {{ .Values.gateway.listener.port }}
      {{- if .Values.gateway.listener.hostname }}
      hostname: {{ .Values.gateway.listener.hostname }}
      {{- end }}
      allowedRoutes:
        namespaces:
          from: Same
    {{- if .Values.gateway.tls.enabled }}
    - name: https
      protocol: HTTPS
      port: 443
      {{- if .Values.gateway.listener.hostname }}
      hostname: {{ .Values.gateway.listener.hostname }}
      {{- end }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .Values.gateway.tls.secretName }}
            kind: Secret
      allowedRoutes:
        namespaces:
          from: Same
    {{- end }}
{{- end }}
