{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: food-app-routes
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "food-app.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
  {{- if and .Values.gateway.hostnames (gt (len .Values.gateway.hostnames) 0) }}
  hostnames:
    {{- range .Values.gateway.hostnames }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.gateway.routes }}
    - matches:
        - path:
            type: PathPrefix
            value: {{ .path }}
      backendRefs:
        - name: {{ .backend.name }}
          port: {{ .backend.port }}
    {{- end }}
{{- end }}
