{{- if and .Values.secrets.enabled (not .Values.secrets.external.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.recipeSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "food-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  NEXT_PUBLIC_API_URL: {{ .Values.secrets.recipeSecret.data.NEXT_PUBLIC_API_URL | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.mongoSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "food-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_URI: {{ .Values.secrets.mongoSecret.data.MONGO_URI | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.rabbitmqSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "food-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  RABBITMQ_URL: {{ .Values.secrets.rabbitmqSecret.data.RABBITMQ_URL | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.jwtSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "food-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_KEY: {{ .Values.secrets.jwtSecret.data.JWT_KEY | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.recipePostgresSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "food-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.recipePostgresSecret.data.DATABASE_URL | quote }}
  POSTGRES_USER: {{ .Values.secrets.recipePostgresSecret.data.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.recipePostgresSecret.data.POSTGRES_PASSWORD | quote }}
  POSTGRES_DB: {{ .Values.secrets.recipePostgresSecret.data.POSTGRES_DB | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.ingredientPostgresSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "food-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.ingredientPostgresSecret.data.DATABASE_URL | quote }}
  DB_HOST: {{ .Values.secrets.ingredientPostgresSecret.data.DB_HOST | quote }}
  POSTGRES_USER: {{ .Values.secrets.ingredientPostgresSecret.data.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.ingredientPostgresSecret.data.POSTGRES_PASSWORD | quote }}
  POSTGRES_DB: {{ .Values.secrets.ingredientPostgresSecret.data.POSTGRES_DB | quote }}
  NODE_ENV: {{ .Values.secrets.ingredientPostgresSecret.data.NODE_ENV | quote }}
  DB_SYNCHRONIZE: {{ .Values.secrets.ingredientPostgresSecret.data.DB_SYNCHRONIZE | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.userprofilePostgresSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "food-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.userprofilePostgresSecret.data.DATABASE_URL | quote }}
  DB_HOST: {{ .Values.secrets.userprofilePostgresSecret.data.DB_HOST | quote }}
  POSTGRES_USER: {{ .Values.secrets.userprofilePostgresSecret.data.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.userprofilePostgresSecret.data.POSTGRES_PASSWORD | quote }}
  POSTGRES_DB: {{ .Values.secrets.userprofilePostgresSecret.data.POSTGRES_DB | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.s3Secret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "food-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_REGION: {{ .Values.secrets.s3Secret.data.AWS_REGION | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.s3Secret.data.AWS_ACCESS_KEY_ID | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.s3Secret.data.AWS_SECRET_ACCESS_KEY | quote }}
  AWS_S3_BUCKET: {{ .Values.secrets.s3Secret.data.AWS_S3_BUCKET | quote }}
{{- end }}
